services:
  backend:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
        - postgresdb
        - mongodb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DB: ${MONGO_DB}
      SERVER_PORT: ${SERVER_PORT}
      CONTEXT_PATH: ${CONTEXT_PATH}

  postgresdb:
    image: postgres:13
    container_name: postgresdb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:7.0.17
    container_name: mongodb-7.0
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
        MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - "27017:27017"