server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${CONTEXT_PATH:/api}
spring:
  # PostgreSQL Configuration
  datasource:
    postgresql:
      jdbc-url: jdbc:postgresql://postgresdb:5432/${POSTGRES_DB}
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      driver-class-name: org.postgresql.Driver
      type: com.zaxxer.hikari.HikariDataSource
      connection-timeout: 30000
      maximum-pool-size: 20
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  # MongoDB Configuration
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/${MONGO_DB}

springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
